version: "3"
services:

  db:
    image: postgres:alpine
    volumes:
    - db-data:/var/lib/postgresql/data
    networks:
    - network

  receipt-reader:
    build:
      context: .
    ports:
    - "8080:80"
    networks:
    - network
    depends_on:
    - db
    volumes:
      - ./:/usr/src/app

networks:
  network:

volumes:
  db-data: